config/routes.rb
Rails.application.routes.draw do
  resources :usuarios
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/usuario.rb
class Usuario < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/usuarios_controller.rb
class UsuariosController < ApplicationController
  before_action :set_usuario, only: [:show, :edit, :update, :destroy]

  # GET /usuarios
  # GET /usuarios.json
  def index
    @usuarios = Usuario.all
  end

  # GET /usuarios/1
  # GET /usuarios/1.json
  def show
  end

  # GET /usuarios/new
  def new
    @usuario = Usuario.new
  end

  # GET /usuarios/1/edit
  def edit
  end

  # POST /usuarios
  # POST /usuarios.json
  def create
    @usuario = Usuario.new(usuario_params)

    respond_to do |format|
      if @usuario.save
        format.html { redirect_to @usuario, notice: 'Usuario was successfully created.' }
        format.json { render :show, status: :created, location: @usuario }
      else
        format.html { render :new }
        format.json { render json: @usuario.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /usuarios/1
  # PATCH/PUT /usuarios/1.json
  def update
    respond_to do |format|
      if @usuario.update(usuario_params)
        format.html { redirect_to @usuario, notice: 'Usuario was successfully updated.' }
        format.json { render :show, status: :ok, location: @usuario }
      else
        format.html { render :edit }
        format.json { render json: @usuario.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /usuarios/1
  # DELETE /usuarios/1.json
  def destroy
    @usuario.destroy
    respond_to do |format|
      format.html { redirect_to usuarios_url, notice: 'Usuario was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_usuario
      @usuario = Usuario.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def usuario_params
      params.require(:usuario).permit(:Nome, :CPF, :DataNascimento, :Email, :Telefone, :Endereco, :CEP, :Cidade, :Estado)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/usuarios_helper.rb
module UsuariosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Desafio</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/usuarios/_form.html.erb
<%= form_with(model: usuario, local: true) do |form| %>
  <%= javascript_pack_tag 'form_js' %>

  <% if usuario.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(usuario.errors.count, "error") %> prohibited this usuario from being saved:</h2>

      <ul>
        <% usuario.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :Nome %>
    <%= form.text_field :Nome %>
  </div>

  <div class="field">
    <%= form.label :CPF %>
    <%= form.text_field :CPF %>
  </div>

  <div class="field">
    <%= form.label :DataNascimento %>
    <%= form.date_select :DataNascimento %>
  </div>

  <div class="field">
    <%= form.label :Email %>
    <%= form.text_field :Email %>
  </div>

  <div class="field">
    <%= form.label :Telefone %>
    <%= form.number_field :Telefone %>
  </div>

  <div class="field">
    <%= form.label :Endereco %>
    <%= form.text_field :Endereco %>
  </div>

  <div class="field">
    <%= form.label :CEP %>
    <%= form.text_field :CEP %>
  </div>

  <div class="field">
    <%= form.label :Estado %>
    <%= form.select :Estado, ['PE', 'SP'] %>
    <%#<%= form.text_field :Cidade %>
  </div>

  <div class="field">
    <%= form.label :Cidade %>
    <%= form.radio_button :Cidade, "Recife"%>Recife<br />
    <%= form.radio_button :Cidade, "São Paulo"%>São Paulo<br />
    <%= form.radio_button :Cidade, "Olinda"%>Olinda<br />
    
    
    <%#<%= form.text_field :Estado %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/usuarios/edit.html.erb
<h1>Editing Usuario</h1>

<%= render 'form', usuario: @usuario %>

<%= link_to 'Show', @usuario %> |
<%= link_to 'Back', usuarios_path %>

app/views/usuarios/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Usuarios</h1>

<table>
  <thead>
    <tr>
      <th>Nome</th>
      <th>Cpf</th>
      <th>DataNascimento</th>
      <th>Email</th>
      <th>Telefone</th>
      <th>Endereco</th>
      <th>Cep</th>
      <th>Cidade</th>
      <th>Estado</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @usuarios.each do |usuario| %>
      <tr>
        <td><%= usuario.Nome %></td>
        <td><%= usuario.CPF %></td>
        <td><%= usuario.DataNascimento %></td>
        <td><%= usuario.Email %></td>
        <td><%= usuario.Telefone %></td>
        <td><%= usuario.Endereco %></td>
        <td><%= usuario.CEP %></td>
        <td><%= usuario.Cidade %></td>
        <td><%= usuario.Estado %></td>
        <td><%= link_to 'Show', usuario %></td>
        <td><%= link_to 'Edit', edit_usuario_path(usuario) %></td>
        <td><%= link_to 'Destroy', usuario, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Usuario', new_usuario_path %>

app/views/usuarios/new.html.erb
<h1>New Usuario</h1>

<%= render 'form', usuario: @usuario %>

<%= link_to 'Back', usuarios_path %>

app/views/usuarios/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @usuario.Nome %>
</p>

<p>
  <strong>Cpf:</strong>
  <%= @usuario.CPF %>
</p>

<p>
  <strong>DataNascimento:</strong>
  <%= @usuario.DataNascimento %>
</p>

<p>
  <strong>Email:</strong>
  <%= @usuario.Email %>
</p>

<p>
  <strong>Telefone:</strong>
  <%= @usuario.Telefone %>
</p>

<p>
  <strong>Endereco:</strong>
  <%= @usuario.Endereco %>
</p>

<p>
  <strong>Cep:</strong>
  <%= @usuario.CEP %>
</p>

<p>
  <strong>Cidade:</strong>
  <%= @usuario.Cidade %>
</p>

<p>
  <strong>Estado:</strong>
  <%= @usuario.Estado %>
</p>

<%= link_to 'Edit', edit_usuario_path(@usuario) %> |
<%= link_to 'Back', usuarios_path %>